# Generated by Django 2.2.4 on 2019-12-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='问题描述', max_length=1024)),
                ('answer', models.CharField(help_text='答案的选项', max_length=100)),
                ('tips', models.CharField(help_text='tips', max_length=1024)),
                ('pngname', models.CharField(help_text='png', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
