# Generated by Django 2.2.4 on 2019-12-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='访问的ip地址', max_length=20)),
                ('visit_time', models.DateTimeField(auto_now_add=True, help_text='访问时间')),
                ('page', models.ForeignKey(help_text='访问题目页面类型', on_delete=django.db.models.deletion.DO_NOTHING, to='apps.Question')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
        migrations.CreateModel(
            name='AnswerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='访问的ip地址', max_length=30)),
                ('answer', models.CharField(help_text='选择的答案', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='开始时间')),
                ('end_time', models.DateTimeField(help_text='结束时间', null=True)),
                ('question', models.ForeignKey(help_text='访问题目页面类型', on_delete=django.db.models.deletion.DO_NOTHING, to='apps.Question')),
            ],
            options={
                'db_table': 'information',
            },
        ),
    ]
